"""Automated regression gates for the nonaffine differential-vortex Test 2.

The tests intentionally use small cases.  Publication refinement data are
generated by ``test2_differential_vortex.py --phase all
--production-matrix full`` and are not recomputed by the unit-test suite.
"""

from __future__ import annotations

import unittest

import numpy as np

import test2_differential_vortex as test2


class AnalyticReferenceTests(unittest.TestCase):
    def test_analytic_map_F_J_and_pressure_balance(self) -> None:
        audit = test2.analytic_audit()
        self.assertTrue(audit["passed"], audit)

    def test_exact_boundary_pressure(self) -> None:
        angle = np.linspace(0.0, 2.0 * np.pi, 257, endpoint=False)
        boundary = np.column_stack((np.cos(angle), np.sin(angle)))
        self.assertLess(
            float(np.max(np.abs(test2.physical_pressure(boundary)))),
            2.0e-15,
        )


class PrescribedMapTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.case = test2.prescribed_case(12, 1.0, 0.5)

    def test_prescribed_operator_action_and_rank(self) -> None:
        case = self.case
        self.assertTrue(case["raw_positive_jacobians"])
        self.assertTrue(case["spectrum"]["full_rank"])
        self.assertLess(case["errors"]["F"]["all"], 4.0e-2)
        self.assertLess(
            case["errors"]["G"]["physical"]["all"], 1.0e-2
        )
        self.assertLess(
            case["errors"]["DG_represented"]["physical"]["global"],
            8.0e-2,
        )

    def test_exact_increment_recursive_transport(self) -> None:
        case = test2.transport_case(12, 8)
        self.assertLess(case["F_rec_dir_over_direct_error"], 1.0e-10)
        self.assertGreater(case["minimum_recursive_J"], test2.ADMISSIBLE_J)
        self.assertLess(
            max(row["scaled_by_H1"] for row in case["DG_test_actions"]),
            1.0e-10,
        )


class ProductionStepTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        # Four complete nonlinear steps are sufficient for the algebraic,
        # area, energy, and repeatability regression gates.
        cls.case = test2.production_case(
            12, 1.0 / 64.0, 0.5, final_time=1.0 / 16.0
        )

    def test_terminal_closure_independent_divergence_area_energy(self) -> None:
        case = self.case
        self.assertTrue(case["passed"], case.get("failure"))
        self.assertLess(case["final"]["represented_terminal_rms"], 2.0e-10)
        self.assertTrue(
            np.isfinite(case["final"]["independent_divergence"]["all"])
        )
        self.assertLess(case["final"]["area_polygon_relative_error"], 1.0e-5)
        self.assertLess(case["final"]["total_energy_relative_error"], 1.0e-5)

    def test_deterministic_repeatability(self) -> None:
        repeated = test2.production_case(
            12, 1.0 / 64.0, 0.5, final_time=1.0 / 16.0
        )
        self.assertTrue(repeated["passed"])
        np.testing.assert_array_equal(
            self.case["final_fields"]["position"],
            repeated["final_fields"]["position"],
        )
        np.testing.assert_array_equal(
            self.case["final_fields"]["velocity"],
            repeated["final_fields"]["velocity"],
        )

    def test_temporal_self_difference_recovers_known_order(self) -> None:
        disc = test2.build_discretization(12)
        cases = []
        for dt in (1.0 / 8.0, 1.0 / 16.0, 1.0 / 32.0, 1.0 / 64.0):
            angle = dt**2
            rotation = np.asarray(
                [
                    [np.cos(angle), -np.sin(angle)],
                    [np.sin(angle), np.cos(angle)],
                ]
            )
            cases.append(
                {
                    "configuration": {"dt": dt},
                    "final_fields": {
                        "position": disc.points @ rotation.T,
                        "velocity": disc.points + dt**2,
                        "pressure": np.sum(
                            disc.points[disc.interior] ** 2, axis=1
                        )
                        + dt**2,
                        "cumulative_F": np.broadcast_to(
                            np.eye(2) + dt**2, (len(disc.points), 2, 2)
                        ).copy(),
                        "cumulative_J": np.ones(len(disc.points)) + dt**2,
                    },
                }
            )
        audit = test2.temporal_self_convergence(cases, layers=12)
        self.assertTrue(audit["available"])
        for row in audit["metrics"].values():
            self.assertAlmostEqual(row["global_rate"], 2.0, delta=1.0e-5)

    def test_pressure_coefficient_mixed_term_fit(self) -> None:
        cases = []
        quadratic_coefficient = 0.04
        for layers in (12, 18, 24):
            disc = test2.build_discretization(layers)
            h = 1.0 / layers
            for dt in test2.TEMPORAL_DTS:
                # This construction gives exactly
                # p_dt-p_dt/2 = h^2 dt + 0.04 dt^2.
                value = (
                    2.0 * h**2 * dt
                    + (4.0 / 3.0) * quadratic_coefficient * dt**2
                )
                cases.append(
                    {
                        "passed": True,
                        "configuration": {
                            "layers": layers,
                            "theta": 0.5,
                            "dt": dt,
                        },
                        "final_fields": {
                            "pressure": np.full(
                                len(disc.interior), value, dtype=np.float64
                            )
                        },
                    }
                )
        audit = test2.pressure_coefficient_mixed_term_audit(cases)
        self.assertTrue(audit["passed"], audit)
        self.assertAlmostEqual(
            audit["observed_spatial_rate_of_a_h"], 2.0, delta=1.0e-10
        )
        self.assertLess(audit["relative_spread_of_b_h"], 1.0e-10)


if __name__ == "__main__":
    unittest.main()
